name: Build Minesweeper Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Create app image using jpackage
        run: |
          jpackage \
            --type app-image \
            --name Minesweeper \
            --input app/build/libs \
            --main-jar app.jar \
            --main-class minesweeper.java.App \
            --icon app/src/main/resources/icon/technology.png \
            --dest output \
            --app-version 1.0

      - name: Create Debian installer using jpackage
        run: |
          jpackage \
            --type deb \
            --name Minesweeper \
            --input app/build/libs \
            --main-jar app.jar \
            --main-class minesweeper.java.App \
            --icon app/src/main/resources/icon/technology.png \
            --dest output \
            --app-version 1.0 \
            --linux-shortcut \
            --linux-menu-group "Games" \
            --linux-package-name minesweeper

      - name: Upload Debian package artifact
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper-deb
          path: output/*.deb

      - name: Upload app image artifact
        uses: actions/upload-artifact@v4
        with:
          name: minesweeper-app-image
          path: output/Minesweeper
